### ISSUE TITLE
Fixing the door - door closer

### ISSUE THREAD

**Issue by finnhodgkin** [foundersandcoders/london-money#18]
We were thinking of trying to fix the front door by adding a door closer. They range in price from about 20- ~100 and look quite easy to install. 

Here's a couple of reasonably priced models with mostly positive reviews: 

[Briton 121CE](https://www.amazon.co.uk/d/Door-Hardware-Locks/Briton-121CE-SES-Closer-Fixed-Doors/B0036QYOAM/ref=sr_1_1?ie=UTF8&qid=1488818916&sr=8-1&keywords=door+closer) or [Arrone AR3500](http://www.ironmongerydirect.co.uk/products/door_closers_and_controls/overhead_door_closers/16464/arrone_ar3500_traditional_closer/655420?vat=1&shopping=true&rmatt=tsid:1027573%7ccid:293195768%7cagid:18060985448%7ctid:pla-50626277095%7ccrid:66224063528%7cnw:g%7crnd:7674532221759442684%7cdvc:c%7cadp:1o4%7cloc:9046009&gclid=CIvp3I7gsNICFeQW0wodC_YH-g&gclsrc=aw.ds)

**Comment by sofer** [comment]
@finnhodgkin approved.

**Comment by nelsonic** [comment]
@finnhodgkin which of the two door closers did you opt for? 
(_looks like it works really well!_) 👍
