### ISSUE TITLE
Approval to spend £750 on International legal fees

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/london-money#24]
See https://github.com/foundersandcoders/international/issues/18

:+: to indicate your approval or raise any notes and queries below.

**Comment by iteles** [comment]
Worth noting that we think £750 is *excellent* value for what we'll be getting from Patrick and really a *very necessary* expense that will avoid much more than this in expenses later on as we'll get good advice early on in the process.

**Comment by sofer** [comment]
Thanks all for your speedy responses. Taking this forward now.
