### ISSUE TITLE
Inaugural Meeting of Founders & Coders London Campus Finance Committee

### ISSUE THREAD

**Issue by markwilliamfirth** [foundersandcoders/london-money#4]
At the F&C 2017 AGM a provisional London finance committee of the following individuals was formed:
@markwilliamfirth | markwilliamfirth@gmail.com
@jsms90 | jen@foundersandcoders.com
@iteles |  ines@dwyl.io
@nelsonic |  nelson@dwyl.io
@sofer | dan@foundersandcoders.com

The proposal for the inaugural meeting of the Committee is:
**Date:** Monday 27th February
**Time:** 6:30 PM - 7:30 PM
**Venue:** 16 Palmers Road

Calendar invites have been sent to Committee members.

**Confirmed Attendees:**
@markwilliamfirth, @iteles, @sofer, @jsms90 

**Preliminary Agenda** (TBC)
1. Confirmation of our terms of reference
2. Whether the current reporting is sufficient for our needs
3. Budgets for this year (Starting on Feb 1)
4. A separate remuneration Committee to meet once a year?
5. International travel expenses relating to Nazareth
6. How frequently we want to meet
7. Companies House
8. HMRC accounts

If you wish to join the Committee or add an item to the agenda please comment on this issue.

**Comment by jsms90** [comment]
@markwilliamfirth I can't confirm attendance via the calendar invite. Something to do with my foundersandcoders email only being an alias. But I'm coming :)

**Comment by jsms90** [comment]
Uh oh, @sofer we've double booked. We're meeting with Code Your Future on Monday, and I'm hesitant to cancel on them at such short notice :worried: 

Unless you think it would be possible to have the meeting with CYF before this? Germán has requested 5.30.

**Comment by markwilliamfirth** [comment]
@iteles notes from the meeting are [here](https://docs.google.com/document/d/1SsCR1Hx73hgDSAX43eUEXq5S-lPACtzxMFAZo8w4re0/edit)

**Comment by markwilliamfirth** [comment]
Minutes for second meeting [here](https://docs.google.com/document/d/1FkHsF2-jq8a7OqRyrGcilGnj1E8IQkMpx3-YHHDSFi4/edit?usp=sharing)
