### ISSUE TITLE
Moving files from london-programme

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/london-money#7]
Hi finance committee, could one of you please move these files from `london-programme` to `london-money`?

- https://github.com/foundersandcoders/london-programme/blob/master/budget-2016-17.md
- https://github.com/foundersandcoders/london-programme/blob/master/funding-options-july-2016.md

Thank you in advance!

**Comment by rebeccaradding** [comment]
@sofer if this is done, can we remove these from `london-programme`?

**Comment by rebeccaradding** [comment]
@markwilliamfirth update?

**Comment by markwilliamfirth** [comment]
These have been moved

**Comment by rebeccaradding** [comment]
Thank you @markwilliamfirth!
